### PR TITLE
Support shouldHaveReceive

### PR DESCRIPTION
**Pull request by MichaelDemeyer**
Add support to shouldHaveReceive method. I do not add test as it look like already cover by `\PHPStan\Mockery\MockeryBarTest::testShouldReceiveAndHaveReceived`

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, what does this solve when:

1) No tests were previously failing.
2) No new tests were added in this PR.

Thanks!

**Comment by MichaelDemeyer** [comment]
Hello,

The point is to allow the use of `shouldHaveReceived` or `shouldNotHaveReceived` on Mockery mock objects with correct return type.

Currently a call like this one : 
`$this->mockeObject->shouldHaveReceived('myMethod')->twice()` 

trigger this error in phpstan at level 9 :
`Cannot call method twice() on mixed.`

I'm not sure where I can add test for this change ?

Thanks

**Comment by ondrejmirtes** [comment]
The testcases here themselves are used to test the extension, so add some example code for example here https://github.com/phpstan/phpstan-mockery/blob/1.1.x/tests/Mockery/MockeryBarTest.php and make sure it fails without the stub change.

**Comment by MichaelDemeyer** [comment]
Thank you for your help. I have added some tests.
`make tests` do NOT failed without the stub change, however `make phpstan` DO fail, it's seem correct to me.
I had to change `make phpstan` from level 8 to level 9 to trigger the error. All the tests already present pass at level 9 without side effect, I think this change may be acceptable.

Thanks.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
